const {test}=require('node:test');const assert=require('node:assert/strict');const Usage=require('../web/usage.js');
test('view selection keeps local ledger and account-wide history independent',()=>{const a={id:'saved-a',label:'A',usage:{accountId:'backend-a'},tokenPeriods:{today:999},tokenUsage:{daily:[{date:'2026-09-10',tokens:999}]}};const state={accounts:[a],localUsage:{accounts:[{id:'account:backend-a',label:'A',periods:{today:12}},{id:'old',label:'Removed',periods:{today:8}}],daily:[{accountId:'account:backend-a',account:'A',date:'2026-09-10',tokens:12},{accountId:'old',account:'Removed',date:'2026-09-10',tokens:8}]}};assert.equal(Usage.rows(state,'wide')[0].periods.today,999);const local=Usage.rows(state,'local');assert.equal(local[0].periods.today,12);assert.equal(local[0].daily[0].tokens,12);assert.equal(local[1].periods.today,8);assert.equal(local[1].account,undefined);});
test('same local labels never mix accounts with different identities',()=>{const state={accounts:[],localUsage:{accounts:[{id:'a',label:'Same'},{id:'b',label:'Same'}],daily:[{accountId:'a',account:'Same',date:'2026-09-10',tokens:5},{accountId:'b',account:'Same',date:'2026-09-10',tokens:7}]}};assert.deepEqual(Usage.rows(state,'local').map(r=>r.daily[0].tokens),[5,7]);});
test('unavailable local history stays unknown and chart periods respect UTC',()=>{assert.deepEqual(Usage.rows({accounts:[{id:'a',label:'A'}]},'local')[0].periods,{});assert.equal(Usage.series(null,'days7'),null);const now=new Date('2026-09-10T23:00:00Z'),d=[{date:'2026-09-03',tokens:100},{date:'2026-09-04',tokens:20},{date:'2026-09-10',tokens:5},{date:'2026-09-11',tokens:99}];assert.equal(Usage.series(d,'days7',now).reduce((n,r)=>n+r.tokens,0),25);assert.equal(Usage.series(d,'today',now)[0].tokens,5);});
test('long daily history groups compactly without losing token totals',()=>{const daily=Array.from({length:100},(_,i)=>({date:new Date(Date.UTC(2026,0,i+1)).toISOString().slice(0,10),tokens:100}));const s=Usage.series(daily,'allTime',new Date('2026-04-10T12:00:00Z'));assert.ok(s.length<=45);assert.equal(s.reduce((n,r)=>n+r.tokens,0),10000);});
test('empty token charts use only a zero tick, without fractional artifacts',()=>{assert.deepEqual(Usage.tokenAxis(0),{top:1,ticks:[0],empty:true});});
test('low and high usage axes use whole, increasing ticks and cover the data',()=>{for(const max of [1,2,3,4,7,10,999,1000,1001,18805298,10193363778,117020064132]){const axis=Usage.tokenAxis(max);assert.equal(axis.empty,false);assert.ok(axis.top>=max);assert.equal(axis.top,axis.ticks.at(-1));assert.ok(axis.ticks.every(Number.isInteger));assert.ok(axis.ticks.every((n,i)=>i===0||n>axis.ticks[i-1]));}});
test('combined local view includes retained and unassigned history exactly once',()=>{const state={accounts:[{id:'a'},{id:'duplicate'}],localUsage:{totals:{today:30},daily:[{date:'2026-09-10',accountId:'a',tokens:10},{date:'2026-09-10',accountId:'removed',tokens:15},{date:'2026-09-10',accountId:'unassigned',tokens:5}]}};assert.deepEqual(Usage.combined(state,'local').periods,{today:30});assert.deepEqual(Usage.combined(state,'local').daily,[{date:'2026-09-10',tokens:30}]);assert.equal(Usage.combined({accounts:[]},'local').daily,null);});
test('combined account-wide chart deduplicates profiles and uses freshest available history',()=>{const a={id:'a',usage:{accountId:'one'},identity:{email:'a@test'},tokenUsage:{checkedAt:'2026-09-10T00:00:00Z',daily:[{date:'2026-09-09',tokens:10}]}},newer={...a,id:'new',tokenUsage:{checkedAt:'2026-09-10T01:00:00Z',daily:[{date:'2026-09-09',tokens:20}]}},legacy={...a,id:'legacy',usage:null},other={...a,id:'other',identity:{email:'b@test'},usage:{accountId:'two'}};const s={accounts:[a,newer,legacy,other,{id:'missing'}],tokenSummary:{periods:{today:{tokens:null,incomplete:true},days7:{tokens:30},days30:{tokens:30},allTime:{tokens:100}}}};const r=Usage.combined(s,'wide');assert.deepEqual(r.daily,[{date:'2026-09-09',tokens:30}]);assert.deepEqual(r.periods,{today:null,days7:30,days30:30,allTime:100});assert.equal(r.partial,true);assert.equal(Usage.combined({accounts:[{id:'a'}]},'wide').daily,null);});

test('combined chart preserves distinct account IDs sharing an email, matching server totals',()=>{const tokenUsage={checkedAt:'2026-09-10T01:00:00Z',lifetimeTokens:10,daily:[{date:'2026-09-10',tokens:10}]};const accounts=[{id:'a',usage:{accountId:'a'}},{id:'b',usage:{accountId:'b'}},{id:'legacy'}].map(a=>({...a,identity:{email:'same@test'},tokenUsage}));const tokenSummary=require('../scripts/tokens.cjs').tokenSummary(accounts,new Date('2026-09-10T01:00:00Z'));const total=Usage.combined({accounts,tokenSummary},'wide');assert.equal(total.daily[0].tokens,total.periods.today);assert.equal(total.periods.today,30);});
