'use strict';
const $=id=>document.getElementById(id);
const token=location.hash.slice(1)||sessionStorage.getItem('account-manager-token');
if(location.hash){sessionStorage.setItem('account-manager-token',token);history.replaceState(null,'',location.pathname);}
const paths={eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12 M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0 M3 3l18 18',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',search:'M16 10a6 6 0 1 1-12 0 6 6 0 0 1 12 0 M15 15l6 6',plus:'M12 4v16 M4 12h16',download:'M12 3v13 M6 10l6 6 6-6 M3 16v5h18v-5',chart:'M4 20v-5 M8 20V8 M12 20V3 M16 20v-9 M20 20V6',chevron:'M9 5l7 7-7 7',switch:'M4 8a8 8 0 0 1 13-3l3 3 M20 3v5h-5 M20 16a8 8 0 0 1-13 3l-3-3 M4 21v-5h5',refresh:'M4 8a8 8 0 0 1 13-3l3 3 M20 3v5h-5 M20 16a8 8 0 0 1-13 3l-3-3 M4 21v-5h5',more:'M5 12h.1 M12 12h.1 M19 12h.1',info:'M12 11v6 M12 7h.01 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0'};
function icon(name){const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('class','icon');s.setAttribute('aria-hidden','true');const p=document.createElementNS(s.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.info);if(name==='more'){p.setAttribute('stroke-width','3.5');}s.append(p);return s;}
for(const n of document.querySelectorAll('[data-icon]'))n.append(icon(n.dataset.icon));
const readPref=(key,fallback)=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
function pref(key,value){try{localStorage.setItem(key,value);}catch{}}
let privacy=readPref('account-manager-privacy','off')==='on';
let state=null,selectedId=readPref('account-manager-selected','all'),view=readPref('account-manager-usage-view','wide'),period='days30',formMode='connect',replaceId=null,switchId=null,removeId=null,menuId=null,submitting=false,noticeTimer,lastOperation='',lastSidebar='';
if(!['wide','local'].includes(view))view='wide';
const colors=['#628aad','#4aab7c','#995ccd','#b77b35','#638d92'];
function el(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=safe(text);if(cls)n.className=cls;return n;}
function name(a){return Privacy.name(a,state,privacy);}
function email(a){return Privacy.email(a,privacy);}
function accountPlan(a){const plan=a?.identity?.planType;return typeof plan==='string'&&plan.trim()?plan.replace(/[_-]+/g,' ').replace(/\b[a-z]/g,c=>c.toUpperCase()):'Plan N/A';}
function safe(text){return Privacy.redact(text,state,privacy);}
function initial(a){return privacy?(name(a).match(/\d+$/)?.[0]||'•'):(a?.label||'?').trim()[0].toUpperCase();}
function color(a){const i=state?.accounts.findIndex(x=>x.id===a?.id)??0;return colors[Math.max(0,i)%colors.length];}
function avatar(a,small=false){const n=el('span',initial(a),'avatar'+(small?' small':''));n.style.setProperty('--avatar',color(a));return n;}
const usageValue=(n,key)=>view==='wide'&&key==='today'&&n==null?'Not reported':compact(n);
const full=n=>n==null?'N/A':new Intl.NumberFormat().format(n);
function compact(n){if(n==null)return 'N/A';if(n===0)return '0';for(const [value,suffix]of [[1e12,'T'],[1e9,'B'],[1e6,'M'],[1e3,'K']])if(n>=value)return (n/value).toFixed(n/value>=100?0:n/value>=10?1:2).replace(/\.0+$/,'')+suffix;return String(n);}
function date(ts){return typeof ts==='number'?new Date(ts*1000).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'N/A';}
function duration(mins){return mins===10080?'Weekly':mins===300?'5-hour':mins?`${mins/60}-hour`:'Usage';}
function windowFor(a){const bucket=a?.usage?.buckets?.find(b=>b.id==='codex')||a?.usage?.buckets?.[0];return [bucket?.primary,bucket?.secondary].find(w=>w?.windowDurationMins===10080)||bucket?.primary||null;}
function meter(w){const p=el('progress');p.max=100;p.value=w?.remainingPercent??0;p.setAttribute('aria-label',duration(w?.windowDurationMins)+' quota remaining');if(w?.remainingPercent!=null&&w.remainingPercent<15)p.className='low';return p;}
const allSelected=()=>selectedId==='all';
function usageSelection(){return allSelected()?Usage.combined(state,view):Usage.rows(state,view).find(r=>r.id===selectedId);}
function renderScope(){const control=$('account-scope'),options=[['all','All accounts'],...state.accounts.map(a=>[a.id,name(a)])],signature=JSON.stringify(options);if(control.dataset.signature!==signature){control.replaceChildren(...options.map(([id,label])=>{const option=el('option',label);option.value=id;return option;}));control.dataset.signature=signature;}control.value=selectedId;$('overview').setAttribute('aria-current',String(allSelected()));}
const selected=()=>state?.accounts.find(a=>a.id===selectedId);
function select(id){if(sessionPage)closeSessions();selectedId=id;pref('account-manager-selected',id);closeMenu();render();}
async function request(route,data){const r=await fetch('/api/'+route,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error);return result;}
function notice(message,error=false){clearTimeout(noticeTimer);$('notice').hidden=!message;$('notice').textContent=privacy?(error?'Action failed. Turn off Screenshot privacy to see details.':'Account action completed.'):message;$('notice').className=error?'error':'';if(message&&!error)noticeTimer=setTimeout(()=>$('notice').hidden=true,6000);}
function showInfo(title,nodes){$('info-title').textContent=safe(title);$('info-content').replaceChildren(...nodes);$('info-dialog').showModal();}
function closeMenu(){$('action-menu').hidden=true;}
function menu(id,anchor){menuId=id;const m=$('action-menu');m.hidden=false;const r=anchor.getBoundingClientRect();m.style.left=Math.max(8,Math.min(innerWidth-218,r.right-210))+'px';m.style.top=Math.max(8,Math.min(innerHeight-175,r.bottom+5))+'px';m.querySelector('button').focus();}
function more(a){const b=el('button',null,'icon-button more');b.append(icon('more'));b.setAttribute('aria-label','Actions for '+name(a));b.setAttribute('aria-haspopup','menu');b.disabled=state?.operation?.status==='running';b.onclick=e=>{e.stopPropagation();menu(a.id,b);};return b;}
function renderSidebar(){
  const query=$('search').value.trim().toLowerCase(),signature=JSON.stringify([state.accounts,selectedId,query,state.operation?.status,privacy]);if(signature===lastSidebar)return;lastSidebar=signature;
  const rows=[];for(const a of state.accounts.filter(a=>(name(a)+' '+(privacy?'':a.identity?.email)).toLowerCase().includes(query))){
    const row=el('div',null,'account-item'),button=el('button',null,'account-select');button.setAttribute('aria-label','View '+name(a));button.setAttribute('aria-current',String(a.id===selectedId));button.onclick=()=>select(a.id);button.append(avatar(a));
    const body=el('span'),line=el('span',null,'account-line'),label=el('span',name(a),'account-name');label.title=name(a);const plan=el('span',accountPlan(a),'plan-badge');plan.title='Account plan: '+accountPlan(a);line.append(label,plan);if(a.current)line.append(el('span','Current','current-badge'));body.append(line,el('span',email(a),'account-email'));
    const w=windowFor(a),q=el('span',null,'mini-quota');q.append(meter(w),el('span',w?.remainingPercent==null?'N/A':Math.round(w.remainingPercent)+'%'));body.append(q);
    const reset=el('span',null,'mini-reset-date');reset.append('Resets ',el('span',date(w?.resetsAt)));reset.title=typeof w?.resetsAt==='number'?`${duration(w.windowDurationMins)} quota reset: ${new Date(w.resetsAt*1000).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'long'})}`:'Reset date unavailable. Refresh usage to check.';body.append(reset);
    const n=a.usage?.resets?.availableCount,r=el('span',null,'mini-reset');r.append(icon('refresh'),el('span',a.status==='reconnect'?'Reconnect required':n==null?'Reset credits: N/A':`${n} reset credit${n===1?'':'s'}`));body.append(r);button.append(body);row.append(button,more(a));rows.push(row);
  }if(!rows.length)rows.push(el('p',query?'No matching accounts':'Connect or save your first account','empty'));$('accounts').replaceChildren(...rows);$('account-count').textContent='Accounts · '+state.accounts.length;
}
function renderQuota(a){
  const w=windowFor(a),pct=w?.remainingPercent;$('quota-title').textContent=duration(w?.windowDurationMins)+' quota';$('quota-value').textContent=pct==null?'N/A':Math.round(pct)+'%';$('quota-meter').value=pct??0;$('quota-meter').className=pct!=null&&pct<15?'low':'';
  const reset=$('quota-reset');reset.replaceChildren();if(w?.resetsAt){reset.append('Resets ',el('em',date(w.resetsAt)));const hours=Math.max(0,Math.ceil((w.resetsAt*1000-Date.now())/3600000));reset.append(` (${Math.floor(hours/24)} days, ${hours%24} hours)`);}else reset.textContent=safe(a?.error)||'Refresh usage to check';
  $('quota-used').textContent=a?.stale?'Last checked':pct==null?'':'Used '+Math.round(100-pct)+'%';const n=a?.usage?.resets?.availableCount;$('reset-count').textContent=n??'N/A';$('reset-copy').textContent=n==null?'Availability not checked':n===0?'No reset credits available':'Redeem in Codex’s account menu';$('use-reset').title=n>0?'Redeem available resets in Codex’s account menu':'No available reset credits';
}
function drawChart(daily){
  if(view==='wide'&&period==='today'&&Array.isArray(daily)&&!daily.some(d=>d.date===new Date().toISOString().slice(0,10))){$('chart').replaceChildren(el('p','Today’s account-wide tokens have not been reported. Switch to This Mac for local usage.','empty'));$('chart').setAttribute('aria-label','Today’s account-wide usage is not reported');return;}
  const data=Usage.series(daily,period),host=$('chart');host.replaceChildren();if(data===null){host.append(el('p','No daily history available. Refresh usage to check.','empty'));return;}
  const ns='http://www.w3.org/2000/svg',s=document.createElementNS(ns,'svg'),W=Math.max(260,host.clientWidth),H=host.clientHeight||180,L=40,R=5,T=5,B=25,P=W-L-R,PH=H-T-B;s.setAttribute('viewBox',`0 0 ${W} ${H}`);s.setAttribute('preserveAspectRatio','none');
  function add(tag,attrs,text){const n=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!=null)n.textContent=safe(text);s.append(n);return n;}
  const axis=Usage.tokenAxis(Math.max(0,...data.map(d=>d.tokens))),top=axis.top;
  for(let i=0;i<4;i++){const y=T+PH-i*PH/3;add('line',{x1:L,x2:W-R,y1:y,y2:y,class:'grid'});if(axis.ticks[i]!=null)add('text',{x:L-8,y:y+4,'text-anchor':'end'},compact(axis.ticks[i]));}
  if(axis.empty)add('text',{x:L+P/2,y:T+PH/2,'text-anchor':'middle'},'No recorded tokens in this period');
  const barWidth=P/Math.max(data.length,1),labelEvery=Math.max(1,Math.ceil(data.length/Math.max(2,Math.floor(P/65))));
  data.forEach((d,i)=>{const x=L+i*barWidth+barWidth*.18,height=d.tokens/top*PH;add('line',{x1:L+i*barWidth,x2:L+i*barWidth,y1:T,y2:T+PH,class:'grid'});const b=add('rect',{x,y:T+PH-height,width:barWidth*.64,height:Math.max(d.tokens>0?1:0,height),rx:.5,class:'bar'});const title=document.createElementNS(ns,'title');title.textContent=d.date+(d.date!==d.endDate?' – '+d.endDate:'')+': '+full(d.tokens)+' tokens';b.append(title);if(i%labelEvery===0){const label=new Date(d.date+'T00:00:00Z').toLocaleDateString(undefined,{month:'short',day:'numeric',timeZone:'UTC'});add('text',{x:L+(i+.5)*barWidth,y:H-5,'text-anchor':'middle'},label);}});
  add('line',{x1:L,x2:W-R,y1:T+PH,y2:T+PH,class:'axis'});host.append(s);host.setAttribute('aria-label',`${$('chart-title').textContent}, ${data.length} date buckets, ${full(data.reduce((n,d)=>n+d.tokens,0))} reported tokens`);
}
function renderUsage(a){
  const rows=Usage.rows(state,view),row=usageSelection(),local=state.localUsage;
  $('view-local').setAttribute('aria-pressed',String(view==='local'));$('view-wide').setAttribute('aria-pressed',String(view==='wide'));for(const b of document.querySelectorAll('[data-period]'))b.setAttribute('aria-pressed',String(b.dataset.period===period));
  $('usage-subtitle').textContent=allSelected()?(view==='wide'?'Combined usage across all saved accounts and devices.':'Total usage on this Mac, including removed accounts and unassigned history.'):(view==='wide'?'Account-wide usage across all your devices.':'Local usage on this Mac. History stays when accounts are removed.');
  const labels=['Tokens today','Last 7 days','Last 30 days',view==='local'?'All recorded':'All time'];$('metrics').replaceChildren(...Usage.keys.map((key,i)=>{const d=el('div',null,'metric');d.append(el('p',labels[i]));const value=el('strong',usageValue(row?.periods?.[key],key));value.title=full(row?.periods?.[key])+' tokens';if(view==='wide'&&key==='today'&&row?.periods?.[key]==null){value.className='not-reported';value.title='No token count has been reported for today’s UTC date. This Mac shows local recordings.';}d.append(value);return d;}));
  $('chart-title').textContent=period==='allTime'?'Token usage (available daily history)':`Daily token usage (${period==='today'?'today':period==='days7'?'last 7 days':'last 30 days'})`;
  $('history-status').textContent=safe(view==='wide'?(row?.error|| (row?.stale?'Last checked data':'')):(local?.error|| (local?.pendingBytes?'Importing local history…':'')));
  if(allSelected()&&row?.partial)$('history-status').textContent='Partial total · Some account usage is unavailable';
  const unreportedToday=view==='wide'&&Array.isArray(row?.daily)&&row?.periods?.today==null;
  if(unreportedToday)$('history-status').textContent='Today not reported · This Mac shows local counts';
  drawChart(row?.daily??null);
  $('chart-note').textContent=view==='local'?'UTC dates · Earlier or uncertain activity remains in Unassigned history.': 'UTC dates · Counts include cached input. Missing dates have no reported tokens.';
  const trRows=[];for(const r of rows){const tr=el('tr'),td=el('td'),button=el('button',null,'table-account');button.append(avatar(r.account||r,true),el('span',name(r.account||r)));button.title=name(r.account||r);if(r.account)button.onclick=()=>select(r.id);else{button.onclick=()=>showInfo(name(r),[el('p',r.unassigned?'These local events have no reliable account attribution. They are included in this Mac’s total.':'This account was removed. Its local usage remains in the total.')]);}td.append(button);if(!r.account)td.append(el('span',r.unassigned?'Unassigned history':'Removed · history retained','row-note'));tr.append(td);for(const k of Usage.keys){const cell=el('td',usageValue(r.periods?.[k],k));cell.title=full(r.periods?.[k])+' tokens';tr.append(cell);}const action=el('td');if(r.account){const b=more(r.account);b.className='table-more';action.append(b);}tr.append(action);trRows.push(tr);}if(!trRows.length){const tr=el('tr'),td=el('td','No accounts to compare','empty');td.colSpan=6;tr.append(td);trRows.push(tr);}$('comparison-rows').replaceChildren(...trRows);
  const total=el('tr'),n=el('td'),label=el('span',null,'total-name');label.append(el('b','∑'),el('span','Total'));n.append(label);total.append(n);for(const k of Usage.keys){const count=view==='local'?local?.totals?.[k]:state.tokenSummary?.periods?.[k]?.tokens;const td=el('td',usageValue(count,k));td.title=full(count)+' tokens';total.append(td);}total.append(el('td'));$('comparison-total').replaceChildren(total);$('all-time-heading').textContent=view==='local'?'All recorded tokens':'All time tokens';
  const partial=view==='wide'&&Usage.keys.some(k=>state.tokenSummary?.periods?.[k]?.incomplete),stale=view==='wide'&&Usage.keys.some(k=>state.tokenSummary?.periods?.[k]?.staleAccounts);$('coverage').hidden=!(partial||stale||view==='local');$('coverage').textContent=view==='local'?'This Mac total includes retained and unassigned history.':partial?'Partial total · Some accounts have unavailable token history.':stale?'Totals include last checked data. Refresh usage for current values.':'';
  $('coverage').title=$('coverage').textContent;
  const checked=view==='wide'?(allSelected()?row?.checkedAt:a?.tokenUsage?.checkedAt):local?.scannedAt?new Date(local.scannedAt*1000).toISOString():null;$('checked').textContent=checked?(allSelected()&&view==='wide'?'Oldest account check ':'Last updated ')+new Date(checked).toLocaleString(undefined,{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Not yet checked';$('footer-copy').textContent=view==='wide'?(allSelected()?'Combined account-wide usage counts each identified account once.':'Account-wide usage covers all devices for this account. · Switching reopens Codex.'):'Local history is retained when accounts are removed. · Switching reopens Codex.';
}
function render(){if(!state)return;$('privacy').setAttribute('aria-pressed',String(privacy));$('privacy-label').textContent=privacy?'Privacy on · Show identities':'Screenshot privacy';if(!allSelected()&&!selected()){selectedId='all';pref('account-manager-selected',selectedId);}const a=selected(),active=state.accounts.find(a=>a.current);renderSidebar();renderScope();$('selected-name').textContent=allSelected()?'All accounts':a?name(a):'Your accounts';$('selected-name').title=a?name(a):'';$('selected-email').textContent=a?email(a)+' · '+accountPlan(a):`${state.accounts.length} saved accounts · Combined token usage`;$('selected-avatar').textContent=allSelected()?'∑':a?initial(a):'+';$('selected-avatar').style.setProperty('--avatar',color(a));$('current-login').textContent='Current login: '+(active?name(active):'Not saved')+'⌄';$('current-login').title=active?name(active):'Save current login';const busy=state.operation?.status==='running';$('switch-label').textContent=a?.current?'Current account':a?.status==='reconnect'?'Reconnect account':'Switch & reopen';$('switch').disabled=!a||!!a.current||busy;$('account-menu').disabled=!a||busy;for(const id of ['refresh','save','connect'])$(id).disabled=busy;$('refresh-label').textContent=busy&&state.operation.type==='refresh'?'Refreshing…':'Refresh usage';document.querySelector('.quota-grid').hidden=allSelected();$('switch').hidden=allSelected();$('account-menu').hidden=allSelected();renderQuota(a);renderUsage(a);
  const operation=JSON.stringify(state.operation);if(operation!==lastOperation){const initial=!lastOperation;lastOperation=operation;if(!initial&&state.operation?.status==='error')notice(state.operation.message,true);else if(!initial&&state.operation?.status==='complete')notice(state.operation.message||'Usage refreshed.');}
  if(state.login?.status==='waiting'&&state.login.authUrl){$('auth-link').href=state.login.authUrl;if(!$('login-dialog').open)$('login-dialog').showModal();}if(state.login&&['complete','error','cancelled'].includes(state.login.status)&&$('login-dialog').open){$('login-dialog').close();notice(state.login.status==='complete'?'Account connected and saved.':state.login.error||'Connection cancelled.',state.login.status==='error');}
}
function form(mode,a){formMode=mode;replaceId=a?.id||null;$('label').type=privacy?'password':'text';$('label').value=privacy?'':a?.label||'';$('form-error').textContent='';$('form-title').textContent=mode==='rename'?'Rename '+name(a):mode==='save'?'Save current account':a?'Reconnect account':'Connect account';$('form-copy').textContent=mode==='rename'?'Choose a display name. Your login and usage history stay unchanged.':mode==='save'?'Save the account currently selected in Codex.':'Sign in with ChatGPT to save this account on your Mac.';$('form-submit').textContent=mode==='rename'?'Save name':mode==='save'?'Save account':'Continue to sign-in';$('form-dialog').showModal();$('label').focus();}
$('privacy').onclick=()=>{privacy=!privacy;pref('account-manager-privacy',privacy?'on':'off');$('search').value='';closeMenu();$('notice').hidden=true;for(const id of ['label','form-error','remove-identity','remove-error','info-title','info-content']){const n=$(id);if('value'in n)n.value='';else n.textContent='';}$('switch-title').textContent='Switch account';$('remove-title').textContent='Remove account?';$('form-title').textContent='Account name';render();renderSessions();};
$('menu-rename').onclick=()=>{closeMenu();form('rename',state.accounts.find(a=>a.id===menuId));};
async function load(){try{[state,sessionData]=await Promise.all([request('state'),request('sessions')]);render();renderSessions();}catch(e){notice(e.message,true);}}
async function refresh(id){try{await request('refresh',id?{id}:{});await load();}catch(e){notice(e.message,true);}}
$('refresh').onclick=()=>refresh();$('save').onclick=()=>form('save');$('connect').onclick=()=>form('connect');$('search').oninput=()=>renderSidebar();$('overview').onclick=()=>{select('all');window.scrollTo({top:0,behavior:'smooth'});};$('account-scope').onchange=()=>select($('account-scope').value);$('current-login').onclick=()=>{const a=state.accounts.find(a=>a.current);if(a)select(a.id);else form('save');};
$('view-local').onclick=()=>{view='local';pref('account-manager-usage-view',view);render();};$('view-wide').onclick=()=>{view='wide';pref('account-manager-usage-view',view);render();};for(const b of document.querySelectorAll('[data-period]'))b.onclick=()=>{period=b.dataset.period;render();};
$('account-menu').onclick=e=>{e.stopPropagation();if(selected())menu(selectedId,$('account-menu'));};$('menu-refresh').onclick=()=>{closeMenu();refresh(menuId);};$('menu-connect').onclick=()=>{closeMenu();form('connect',state.accounts.find(a=>a.id===menuId));};$('menu-remove').onclick=()=>{closeMenu();const a=state.accounts.find(a=>a.id===menuId);if(!a)return;removeId=a.id;$('remove-title').textContent='Remove '+name(a)+'?';$('remove-identity').textContent=email(a);$('remove-error').textContent='';$('remove-dialog').showModal();$('remove-cancel').focus();};
document.addEventListener('click',e=>{if(!$('action-menu').contains(e.target))closeMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='f'&&!document.querySelector('dialog[open]')){e.preventDefault();$('search').focus();}if(!$('action-menu').hidden&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const items=[...$('action-menu').querySelectorAll('button')],i=items.indexOf(document.activeElement);items[(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length].focus();}});
$('switch').onclick=()=>{const a=selected();if(!a)return;if(a.status==='reconnect'){form('connect',a);return;}switchId=a.id;$('switch-title').textContent='Switch to '+name(a);$('switch-dialog').showModal();};$('switch-cancel').onclick=()=>$('switch-dialog').close();$('switch-confirm').onclick=async()=>{try{await request('switch',{id:switchId,reopen:true});$('switch-dialog').close();await load();}catch(e){notice(e.message,true);$('switch-dialog').close();}};
$('form-cancel').onclick=()=>$('form-dialog').close();$('account-form').onsubmit=async e=>{e.preventDefault();if(submitting)return;submitting=true;$('form-submit').disabled=true;$('form-error').textContent='';try{const r=await request(formMode,{label:$('label').value,id:replaceId||undefined});$('form-dialog').close();if(formMode==='save'||formMode==='rename')notice(r.message);await load();}catch(e){$('form-error').textContent=privacy?'Could not save. Use a name of 1–64 characters or turn off privacy for details.':e.message;}finally{submitting=false;$('form-submit').disabled=false;}};
$('login-cancel').onclick=async()=>{try{await request('login/cancel',{});$('login-dialog').close();await load();}catch(e){notice(e.message,true);}};$('login-dialog').addEventListener('cancel',e=>{e.preventDefault();$('login-cancel').click();});$('remove-cancel').onclick=()=>$('remove-dialog').close();$('remove-confirm').onclick=async()=>{const b=$('remove-confirm');if(b.disabled)return;b.disabled=true;$('remove-error').textContent='';try{const r=await request('remove',{id:removeId});$('remove-dialog').close();notice(r.message);await load();}catch(e){$('remove-error').textContent=privacy?'Could not remove this account. Turn off privacy for details.':e.message;}finally{b.disabled=false;}};
$('info-close').onclick=()=>$('info-dialog').close();$('settings').onclick=()=>showInfo('Account Manager',[el('p','Your saved logins and local token history stay on this Mac.'),el('p','The recorder runs while the dashboard service is running, even when its browser tab is closed. Open Account Manager after restarting your Mac to resume.'),el('p','Selecting an account only changes what you are viewing. Switch & reopen changes the login used by Codex.')]);$('reset-info').onclick=()=>{const a=selected(),credits=a?.usage?.resets?.credits||[];showInfo('Reset credits',[el('p','Reset credits are separate from your scheduled quota reset. Redeem available credits in Codex’s account menu for the account signed in there.'),...credits.map(c=>el('p',(c.title||'Reset credit')+(c.expiresAt?' · Expires '+date(c.expiresAt):'')))]);};$('quota-info').onclick=()=>{const a=selected(),nodes=[];for(const b of a?.usage?.buckets||[]){nodes.push(el('h3',b.name||b.id));for(const w of [b.primary,b.secondary].filter(Boolean))nodes.push(el('p',`${duration(w.windowDurationMins)} · ${w.remainingPercent==null?'N/A':Math.round(w.remainingPercent)+'%'} remaining · Resets ${date(w.resetsAt)}`),meter(w));}if(!nodes.length)nodes.push(el('p',a?.error||'No usage limits available. Refresh usage to check.'));showInfo('All usage limits',nodes);};
new ResizeObserver(()=>{if(state){const row=usageSelection();drawChart(row?.daily??null);}}).observe($('chart'));


let sessionData=null,sessionPage=false,onlyActive=false,lastSessions='';
let sessionSort=readPref('account-manager-session-sort','active');
if(!['active','tokens'].includes(sessionSort))sessionSort='active';
const money=n=>n==null?'N/A':n>0&&n<0.01?'< $0.01':new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
function sessionTitle(s,i){return privacy?'Session '+(i+1):s.title;}
function sessionAccount(s){const a=state?.accounts.find(a=>(a.usage?.accountId?'account:'+a.usage.accountId:'profile:'+a.id)===s.accountId);if(a)return name(a);const old=state?.localUsage?.accounts?.find(a=>a.id===s.accountId);return old?name(old):'Unassigned account';}
function sessionMetric(label,value,note){const d=el('div',null,'metric');d.append(el('p',label),el('strong',value),el('span',note,'metric-note'));return d;}
function openSessions(){sessionPage=true;$('account-view').hidden=true;$('sessions-view').hidden=false;$('live-nav').setAttribute('aria-current','page');closeMenu();renderSessions();window.scrollTo({top:0,behavior:'smooth'});}
function closeSessions(){sessionPage=false;$('account-view').hidden=false;$('sessions-view').hidden=true;$('live-nav').removeAttribute('aria-current');render();}
function sessionDetails(s,i){
  const u=s.usage,nodes=[el('p',(privacy?'Project hidden':s.project||'No project')+' · '+sessionAccount(s)),el('p','Latest turn: '+(s.model||'N/A')+' · Reasoning: '+(s.reasoning||'N/A'))];
  const pairs=[['Session total',u.tokens.total_tokens],['Input (includes cache)',u.tokens.input_tokens],['Cached input',u.tokens.cached_input_tokens],['Cache writes',u.tokens.cache_write_input_tokens],['Output (includes reasoning)',u.tokens.output_tokens],['Reasoning output',u.tokens.reasoning_output_tokens],['Latest turn tokens',s.pendingBytes&&!s.turnUsage?.requests?null:s.turnUsage?.tokens.total_tokens]];
  for(const [label,n]of pairs)nodes.push(el('p',label+': '+full(n)));
  nodes.push(el('p','Estimated session cost: '+money(u.cost)+(u.unpricedRequests?' · Partial: '+u.unpricedRequests+' unpriced requests':'')),el('p','Latest turn estimate: '+money(s.turnUsage?.cost)));
  if(s.pendingBytes)nodes.push(el('p','History is still importing. Counts and estimates shown so far are partial.'));
  for(const [model,n]of Object.entries(u.models))nodes.push(el('p',model+': '+full(n)+' tokens'));
  nodes.push(el('p','Session totals can span models and accounts. The account shown belongs to the latest observed turn; uncertain attribution stays unassigned.'),el('p',sessionData.pricing?.basis||''));
  showInfo(sessionTitle(s,i),nodes);
}
function renderSessions(){
  if(!sessionData)return;const all=sessionData.sessions||[],fresh=!!sessionData.scannedAt&&Date.now()/1000-sessionData.scannedAt<=30,active=fresh?all.filter(s=>s.status==='active'):[];$('live-count').textContent=active.length;
  if(!sessionPage)return;
  const rows=[...(onlyActive?active:all)].sort((a,b)=>{
    const activity=sessionSort==='active'&&fresh?Number(b.status==='active')-Number(a.status==='active'):0;
    const tokens=s=>(s.pendingBytes&&!s.usage?.requests)?-1:(s.usage?.tokens?.total_tokens??-1);
    return activity||tokens(b)-tokens(a)||(b.updatedAt||0)-(a.updatedAt||0)||a.id.localeCompare(b.id);
  }),stale=!!sessionData.scannedAt&&Date.now()/1000-sessionData.scannedAt>30;
  const total=rows.reduce((t,s)=>t+s.usage.tokens.total_tokens,0),cost=rows.reduce((t,s)=>t+(s.usage.cost||0),0),priced=rows.some(s=>s.usage.cost!=null),missing=rows.reduce((n,s)=>n+s.usage.unpricedRequests,0),pending=rows.some(s=>s.pendingBytes),input=rows.reduce((n,s)=>n+s.usage.tokens.cached_input_tokens,0);
  $('session-metrics').replaceChildren(sessionMetric('Active sessions',String(stale?0:active.length),stale?'Snapshot is stale':'Recent open turns'),sessionMetric('Session tokens',compact(total),pending?'Partial · importing history':'Total for displayed sessions'),sessionMetric('Cached input',compact(input),'Included in session tokens'),sessionMetric('Est. API cost',money(priced?cost:null),pending||missing?'Partial estimate · USD':'Standard rates · USD'));
  $('sort-active').setAttribute('aria-pressed',String(sessionSort==='active'));$('sort-tokens').setAttribute('aria-pressed',String(sessionSort==='tokens'));
  document.querySelector('.session-table th:nth-child(5)').setAttribute('aria-sort',sessionSort==='tokens'?'descending':'none');
  document.querySelector('.session-table th:nth-child(2)').setAttribute('aria-sort',sessionSort==='active'?'other':'none');
  $('sessions-recent').setAttribute('aria-pressed',String(!onlyActive));$('sessions-active').setAttribute('aria-pressed',String(onlyActive));
  $('session-sync').textContent=sessionData.error||(sessionData.loading?'Reading local sessions…':stale?'Updates delayed · last scan '+date(sessionData.scannedAt):sessionData.pendingBytes?'Importing session history · live status is updating':'Updated '+new Date(sessionData.scannedAt*1000).toLocaleTimeString()+' · refreshes every 5 seconds');
  $('session-scope').textContent=sessionData.scope||'Local session metadata will appear here.';$('session-status-note').textContent=sessionData.statusNote||'';
  const signature=JSON.stringify([rows,privacy,stale]);if(signature===lastSessions)return;lastSessions=signature;
  const statusLabels={active:'Active',finished:'Finished',interrupted:'Interrupted',stale:'No recent signal',unknown:'Unknown'};
  const elements=rows.map(s=>{const i=all.indexOf(s),tr=el('tr'),identity=el('td'),title=el('button',sessionTitle(s,i),'session-title');title.title=sessionTitle(s,i);title.onclick=()=>sessionDetails(s,i);identity.append(title,el('span',(privacy?'Project hidden':s.project||'No project')+' · '+sessionAccount(s),'session-secondary'));tr.append(identity);
    const status=stale?'stale':s.status,st=el('td');st.append(el('span',statusLabels[status]||'Unknown','session-status '+status),el('span',date(s.updatedAt),'session-secondary'));tr.append(st);
    const model=el('td');model.append(el('span',s.model||'N/A'),el('span',s.reasoning?'Reasoning: '+s.reasoning:'Reasoning: N/A','session-secondary'));tr.append(model);
    const tokens=el('td');tokens.append(el('span',compact(s.pendingBytes&&!s.usage.requests?null:s.usage.tokens.input_tokens)+' in'),el('span',compact(s.pendingBytes&&!s.usage.requests?null:s.usage.tokens.output_tokens)+' out','session-secondary'));tokens.title='Input includes '+full(s.usage.tokens.cached_input_tokens)+' cached tokens. Output includes reasoning.';tr.append(tokens);
    const total=el('td');total.append(el('span',compact(s.pendingBytes&&!s.usage.requests?null:s.usage.tokens.total_tokens)));total.title=full(s.usage.tokens.total_tokens)+' tokens';if(s.pendingBytes)total.append(el('span','Importing…','session-secondary'));tr.append(total);
    const cost=el('td');cost.append(el('span',money(s.usage.cost)));if(s.usage.unpricedRequests)cost.append(el('span',s.usage.cost==null?'Rate unavailable':'Partial estimate','session-secondary'));else if(s.pendingBytes)cost.append(el('span','Partial estimate','session-secondary'));tr.append(cost);return tr;});
  if(!elements.length){const tr=el('tr'),td=el('td',sessionData.loading?'Reading local sessions…':onlyActive?'No active sessions right now. Recent sessions remain available.':'No local sessions updated in the last 7 days.','empty');td.colSpan=6;tr.append(td);elements.push(tr);}$('session-rows').replaceChildren(...elements);
}
$('live-nav').onclick=openSessions;$('sessions-back').onclick=closeSessions;$('sessions-recent').onclick=()=>{onlyActive=false;renderSessions();};$('sessions-active').onclick=()=>{onlyActive=true;renderSessions();};

$('sort-active').onclick=()=>{sessionSort='active';pref('account-manager-session-sort',sessionSort);renderSessions();};
$('sort-tokens').onclick=()=>{sessionSort='tokens';pref('account-manager-session-sort',sessionSort);renderSessions();};
load();setInterval(load,1800);
